-- Seed existing blog posts into the database
INSERT INTO blog_posts (title, slug, description, content, author, tags, published, published_at, created_at)
VALUES
(
  'Getting Started with AI eBooks: A Complete Guide',
  'getting-started-with-ai-ebooks',
  'Learn how to create your first AI-powered eBook using AutoBookLab — from importing content to exporting a polished PDF.',
  E'Creating an eBook used to mean weeks of writing, formatting, and design work. With AI-powered tools like AutoBookLab, you can go from a rough idea to a publication-ready book in a single afternoon. Here''s how to get started.\n\n## Step 1: Start with Your Content\n\nAutoBookLab gives you multiple ways to begin. You can write from scratch using the built-in text editor, paste existing content, import a PDF, or even pull in a YouTube video transcript. The platform is designed to work with whatever you already have.\n\nIf you''re starting from zero, try the AI outline generator. Give it your book title and a brief description, and it will create a structured chapter outline that you can refine before generating content.\n\n## Step 2: Generate and Refine with AI\n\nOnce you have your structure, AutoBookLab''s AI can generate full chapter drafts based on your outline. Each chapter generation costs 2 credits, and you can regenerate or rewrite sections until they match your voice and style.\n\nThe AI chat assistant (available on Starter plans and above) lets you have a conversation about your content — ask it to expand on a point, simplify language, or suggest better phrasing. Think of it as a writing partner that''s always available.\n\n## Step 3: Design in the Visual Editor\n\nThis is where AutoBookLab really shines. The visual page editor lets you design every page of your book using drag-and-drop elements. Add headings, images, blockquotes, callouts, tables, and more — then arrange them exactly how you want.\n\nYou can use the "Seed Pages" feature to automatically convert your chapter content into designed pages, or build each page manually from the element library. Either way, you get full control over the final look.\n\n## Step 4: Add Images\n\nSearch millions of royalty-free photos from Unsplash directly within the editor, or upload your own images. On Starter plans and above, you can also generate unique cover art using AI image generation powered by DALL·E 3.\n\n## Step 5: Export and Share\n\nWhen you''re happy with your book, export it as a print-quality PDF or an EPUB file (Starter+). EPUBs are compatible with Kindle, Apple Books, Kobo, and other major eBook platforms. Your exported files are stored in your account for easy re-downloading.\n\n## Getting the Most Out of Your Credits\n\nFree accounts come with 10 credits to get started. Each action has a different credit cost: chapter generation (2 credits), rewriting (1 credit), AI chat (1 credit), and cover image generation (3 credits). Plan your usage around your most important content first, then upgrade when you need more.\n\nReady to create your first eBook? [Sign up for free](/sign-up) and start building today.',
  'AutoBookLab Team',
  ARRAY['guides', 'ai', 'getting-started'],
  true,
  '2026-03-10T00:00:00Z',
  '2026-03-10T00:00:00Z'
),
(
  'Why a Visual Editor Changes Everything for eBook Creation',
  'why-visual-editor-matters',
  'Most eBook tools stop at text. Here''s why a drag-and-drop visual editor makes the difference between an amateur PDF and a professional publication.',
  E'If you''ve ever tried to create an eBook with a standard text editor, you know the frustration. You write great content, but the final output looks like a glorified Word document. That''s because most eBook tools treat design as an afterthought.\n\n## The Problem with Text-Only Tools\n\nTraditional eBook creation follows a two-step process: write your content in one tool, then format it in another. This disconnect means you never see how your book will actually look until the very end — and by then, making design changes means going back and forth between tools.\n\nEven tools that offer "templates" usually just apply a CSS stylesheet to your text. You get consistent fonts and margins, but no real control over page layout, image placement, or visual hierarchy.\n\n## What a Visual Editor Enables\n\nAutoBookLab''s visual page editor works differently. Instead of writing text and hoping the output looks good, you design each page directly. Drag a heading here, place an image there, add a callout box, insert a divider — and see exactly how it will appear in the final book.\n\nThe editor supports 18+ element types, including text blocks, headings, images with captions, blockquotes, tables, author bios, callout boxes, and more. Each element can be positioned, resized, and styled independently.\n\n## Design Meets AI\n\nThe real magic happens when you combine visual design with AI. The "Seed Pages" feature takes your chapter content and automatically creates designed pages with appropriate headings, text blocks, and spacing. It''s like having a book designer who works in seconds.\n\nYou can also use the AI chat to ask for design suggestions, content improvements, or alternative ways to present information — all without leaving the editor.\n\n## Cover Design Without a Designer\n\nFirst impressions matter, and your book cover is the first thing readers see. AutoBookLab includes AI cover image generation powered by DALL·E 3, letting you create unique, professional cover art from a text description. Pair it with the cover page editor to add your title, subtitle, and author name in exactly the right position.\n\n## Export What You See\n\nBecause you''re designing pages visually, the exported PDF looks exactly like what you designed. No surprises, no "why does this look different" moments. EPUB exports maintain your content structure and styling for consistent reading across devices.\n\n## The Bottom Line\n\nA visual editor doesn''t just make your eBooks look better — it makes the entire creation process more intuitive and enjoyable. When you can see your book taking shape as you build it, you make better design decisions and produce more professional results.\n\nWant to try it for yourself? [Create a free account](/sign-up) and explore the visual editor today.',
  'AutoBookLab Team',
  ARRAY['product', 'design', 'visual-editor'],
  true,
  '2026-03-08T00:00:00Z',
  '2026-03-08T00:00:00Z'
);
